substitutions:
  name: "sms-module"
  location: "客厅"  #放置位置

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  friendly_name: "${location}短信模块"
  comment: sms-module
  project:
    name: synodriver.sms-module
    version: "0.0.1"
preferences:
  flash_write_interval: 10min
esp32:
  variant: ESP32C5
  flash_size: 8MB
  framework:
    type: esp-idf


# Enable logging
logger:

# Enable Home Assistant API
api:
  on_client_connected:
    - logger.log:
        format: "Client %s connected to API with IP %s"
        args: ["client_info.c_str()", "client_address.c_str()"]
    # - if:
    #     condition:
    #       binary_sensor.is_on: relay_status
    #     then:
    #       - logger.log: "Power is ON!"
    #       - light.turn_on: stat_led
    #       - delay: 2s
    #     else:
    #       - logger.log: "Power is OFF!"
    #       - light.turn_off: stat_led
ota:
  - platform: esphome
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: ""
  #use_address: 192.168.5.240
captive_portal:

web_server:
  port: 80    

external_components:
  - source:
      type: local
      path: components

debug:
  update_interval: 10s

uart:
  id: uart_bus
  tx_pin: 13
  rx_pin: 14
  baud_rate: 115200
  stop_bits: 1


ml307r:
  id: ml307r_
  uart_id: uart_bus
  update_interval: 10s

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "${name} WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "${name} WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
  
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
    cpu_frequency:
      name: "CPU Frequency"

  - platform: ml307r
    ml307r_id: ml307r_
    signal_strength:
      name: "signal strength"

text_sensor:
  - platform: ml307r
    ml307r_id: ml307r_
    sms_sender:
      name: "sms sender"
    sms_content:
      name: "sms content"
    sms_timestamp:
      name: "sms timestamp"
    network_status:
      name: "network status"

binary_sensor:
  - platform: ml307r
    ml307r_id: ml307r_
    online:
      name: "online"

button:
  - platform: ml307r
    ml307r_id: ml307r_
    soft_shutdown:
      name: "soft shutdown"
    save_shutdown:
      name: "save shutdown"
    soft_reboot:
      name: "soft reboot"
    hard_reboot:
      name: "hard reboot"

  - platform: template
    name: "ping"
    on_press: 
      then:
        - ml307r.ping:
            id: ml307r_
            host: 8.8.8.8
  
  - platform: template
    name: "send at command"
    on_press: 
      then:
        - ml307r.send_at_command:
            id: ml307r_
            cmd: "AT+MCSEARFCN=0"